#AS400 constants
SEARCH_FORWARD = 1
SEARCH_BACKWARD = 2
NO_TIMEOUT = 0
INHIBITED_NO = 0
INHIBITED_SYSTEM_WAIT = 1
INHIBITED_COMMUNICATION_CHECK = 2
INHIBITED_PROGRAM_CHECK = 3
INHIBITED_MACHINE_CHECK = 4
INHIBITED_OTHER = 5